# Generated by Django 2.2.7 on 2019-11-17 16:22

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('dbfid', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('playerclass', models.CharField(db_index=True, max_length=200)),
                ('armor', models.IntegerField(blank=True, null=True)),
                ('artist', models.CharField(blank=True, max_length=200, null=True)),
                ('attack', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cardid', models.CharField(max_length=200)),
                ('cardset', models.CharField(max_length=200)),
                ('collectible', models.BooleanField(blank=True, max_length=200, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('durability', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('elite', models.BooleanField(blank=True, max_length=200, null=True)),
                ('faction', models.CharField(blank=True, max_length=200, null=True)),
                ('flavor', models.CharField(blank=True, max_length=200, null=True)),
                ('health', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.CharField(blank=True, max_length=200, null=True)),
                ('imggold', models.CharField(blank=True, max_length=200, null=True)),
                ('locale', models.CharField(blank=True, max_length=200, null=True)),
                ('mechanics', jsonfield.fields.JSONField(blank=True, null=True)),
                ('race', models.CharField(blank=True, max_length=200, null=True)),
                ('rarity', models.CharField(blank=True, max_length=200, null=True)),
                ('cardtype', models.CharField(max_length=200)),
            ],
        ),
    ]
